package lab16;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author ST 10371978 Tlhonolofatso selepe
 */
public class WelcomeJ extends javax.swing.JFrame {
private String[] developers = new String[100];
    private String[] taskNames = new String[100];
    private String[] taskIDs = new String[100];
    private int[] taskDurations = new int[100];
    private String[] taskStatuses = new String[100];
    private int taskCounter = 0; // Counter to track task numbers
        private int i;
        private boolean round;
    /**
     * Creates new form WelcomeJ
     */
    public WelcomeJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("Add Task");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Show Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Quit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome to EasyKanBan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 showAddTaskDialog();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
JOptionPane.showMessageDialog(null,"Coming Soon");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
 private void showAddTaskDialog() {
    String input = JOptionPane.showInputDialog(null, "Enter the number of tasks:");
    if (input != null) {
        try {
            int numTasks = Integer.parseInt(input);
            if (numTasks > 0) {
                for (int i = 0; i < numTasks; i++) { // Use 'i' consistently
                    JFrame dialog = new JFrame("Add Task");
                    dialog.setSize(400, 300);
                    dialog.setLocationRelativeTo(null);
                    dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                    JPanel panel = new JPanel(new GridLayout(7, 2, 5, 5));
                    panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

                    JTextField taskNameField = new JTextField();
                    JTextField taskDescriptionField = new JTextField();
                    JTextField developerDetailsField = new JTextField();
                    JTextField durationField = new JTextField();

                    JComboBox<String> taskStatusComboBox = new JComboBox<>(new String[]{"To Do", "Done", "Doing"});

                    panel.add(new JLabel("Task Name:"));
                    panel.add(taskNameField);
                    panel.add(new JLabel("Task Description:"));
                    panel.add(taskDescriptionField);
                    panel.add(new JLabel("Developer Details:"));
                    panel.add(developerDetailsField);
                    panel.add(new JLabel("Task Duration (hours):"));
                    panel.add(durationField);
                    panel.add(new JLabel("Task Status:"));
                    panel.add(taskStatusComboBox);

                    JButton submitButton = new JButton("Submit");
                    submitButton.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            String taskName = taskNameField.getText();
                            String taskDescription = taskDescriptionField.getText();
                            String developerDetails = developerDetailsField.getText();
                            String durationInput = durationField.getText();
                            String taskStatus = (String) taskStatusComboBox.getSelectedItem();

                            if (taskName.isEmpty() || taskDescription.isEmpty() || developerDetails.isEmpty() || durationInput.isEmpty()) {
                                JOptionPane.showMessageDialog(null, "All fields are required.");
                                return;
                            }

                            int taskDuration;
                            try {
                                taskDuration = Integer.parseInt(durationInput);
                            } catch (NumberFormatException ex) {
                                JOptionPane.showMessageDialog(null, "Please enter a valid number for task duration.");
                                return;
                            }

                            Task task = new Task(taskName, taskDescription, developerDetails, taskDuration, taskStatus);
                            developers[taskCounter] = developerDetails;
                            taskNames[taskCounter] = taskName;
                            taskIDs[taskCounter] = task.createTaskID();
                            taskDurations[taskCounter] = taskDuration;
                            taskStatuses[taskCounter] = taskStatus;

                            taskCounter++; // Increment the task counter for the next task

                            JOptionPane.showMessageDialog(null, task.printTaskDetails());
                            JOptionPane.showMessageDialog(null, "Task successfully captured");

                            dialog.dispose(); // Close the dialog
                        }
                    });

                    panel.add(submitButton);

                    dialog.add(panel);
                    dialog.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Number of tasks must be greater than zero.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number.");
        }
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}

   
